changeLogFile=db/changelog/db.changelog-master.xml
url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:farm_animals}
username=root
password=root
driver=com.mysql.cj.jdbc.Driver
liquibase.hub.mode=off